---
- hosts: localhost
  gather_facts: true
  become: no
  tasks:
    - name: "Check ansible version >=2.7.8"
      assert:
        msg: "Ansible must be v2.7.8 or higher"
        that:
          - ansible_version.string is version("2.7.8", ">=")
      tags:
        - check
  vars:
    ansible_connection: local

- hosts: redis
  gather_facts: true
  roles:
    - { role: disableselinux}
    - { role: disablefirewalld}
    - { role: preparesysctl}
    - { role: installremi}
    - { role: prepareuser}
    - { role: preparedirectory}
    - { role: installredis}

- hosts: redis[0]
  roles:
    - { role: createrediscluster}