---
- name: install redis
  yum:
    name: "{{ redis_version }}"

- name: stop and disable redis service
  systemd:
    name: redis
    state: stopped
    enabled: no

- name: delete redis service
  ignore_errors: yes
  file: 
    path: "{{ item }}"
    state: absent
  with_items: 
    - /usr/lib/systemd/system/redis.service
    - /etc/systemd/system/redis.service.d
    - /etc/systemd/system/redis-sentinel.service.d

- name: prepare redis config
  template:
    src: config.j2
    dest: "/etc/redis/redis_{{ redis_port }}.conf"
    owner: redis

- name: prepare redis service
  template:
    src: service.j2
    dest: "/etc/systemd/system/redis_{{ redis_port }}.service"
    owner: redis
    group: redis

- name: restart redis service
  systemd:
    name: "redis_{{ redis_port }}"
    daemon_reload: yes
    enabled: yes
    state: restarted