---
- name: Create Cluster debug
  debug:
    msg: redis-cli --cluster-replicas 1 --cluster create {% for redis_node in groups['redis_all'] %} {{ hostvars[redis_node].ip }}:{{ redis_ports }} {% endfor %}
 
- name: Create Cluster
  shell: |
    echo "yes" |redis-cli --cluster-replicas 1 --cluster create {% for redis_node in groups['redis_all'] %} {{ hostvars[redis_node].ip }}:{{ redis_ports }} {% endfor %}
