---
- include_tasks: uninstall.yml
  when: action == 'uninstall' or action == 'reinstall'

- include_tasks: installtools.yml
  when: action == 'install'

- include_tasks: upgrade.yml
  when: action == 'upgrade'

- include_tasks: prepareservice.yml
  when: action == 'install' or action == 'reinstall'

- include_tasks: prepareredisconfig.yml
  when: action != 'uninstall'

- name: Restart Service
  debug:
    msg: restart service
  notify: restart-service
  changed_when: true
  when: action == 'restart'

- meta: flush_handlers

- include_tasks: createcluster.yml
  run_once: true
  when: action == 'install' or action == 'reinstall'