---
- name: Prepare services
  vars:
    redis_port: "{{item}}"
  template:
    src: service.j2
    dest: "/etc/systemd/system/redis_{{item}}.service"
    owner: redis
    group: redis
  with_items: "{{redis_ports}}"