---
- name: prepare directory /etc/redis/**
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: redis
    group: redis
    recurse: yes
  with_items: 
    - "/etc/redis"
    - "/etc/redis/redis_{{ redis_port }}"